In [ ]:
import numpy as np
from time import process_time

In [ ]:
a = [i for i in range(10000000)]
b= process_time()
a = [i+10 for i in a]
c= process_time()
print(c-b)


0.6029022519999998


In [ ]:
x = np.arange(10000000)
b= process_time()
x = x+10
c= process_time()
print(c-b)

0.02879895099999885


In [ ]:
list1 = [4,9,6,6,6,4,98]
print(type(list1))

<class 'list'>


In [ ]:
np_array = np.array(list1)
print(((np_array)))

[ 4  9  6  6  6  4 98]


In [ ]:
#creating a 1d array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
b = np.array([[1,2,3],[4,5,6],[6,8,6]])
print(b)

[[1 2 3]
 [4 5 6]
 [6 8 6]]


In [ ]:
b.shape

(3, 3)

In [ ]:
f = np.array([[1,2,3],[4,5,6]],dtype=float)
print(f)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
zz = np.zeros((3,3),dtype=int)
print(zz)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
c = np.eye(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
q = np.arange(2,10,2)
print(q)

[2 4 6 8]


In [ ]:
n = np.full((5,4),8)
print(n)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [ ]:
n = np.random.random((6,7))
print(n)

[[0.47637119 0.47124336 0.0655709  0.99651549 0.77073131 0.69942305
  0.29873129]
 [0.05725044 0.5168176  0.40288981 0.6811813  0.12271236 0.8667688
  0.60244546]
 [0.35764758 0.6105596  0.72323171 0.77155911 0.65511732 0.82606502
  0.70965603]
 [0.14763181 0.62840639 0.78380241 0.55835022 0.5715772  0.50959273
  0.9345779 ]
 [0.53733967 0.48083078 0.92990493 0.33311623 0.21242012 0.4470757
  0.44342207]
 [0.38653845 0.44438258 0.72946631 0.03733343 0.54865609 0.75715984
  0.16772343]]


In [ ]:
m = np.random.randint(1,20,(2,2))
print(m)
#

[[12 15]
 [18  8]]


In [ ]:
s = np.linspace(1,30,5)
print(s)

[ 1.    8.25 15.5  22.75 30.  ]


In [ ]:
j = np.arange(1,30,5)
print(j)

[ 1  6 11 16 21 26]


In [ ]:
lk = [10,2,6,4,45,7]

np_array = np.asarray(lk)
print(np_array)
type(np_array)

[10  2  6  4 45  7]


numpy.ndarray

In [ ]:
lk = (10,2,6,4,45,7)

np_array = np.asarray(lk)
print(np_array)
type(np_array)

[10  2  6  4 45  7]


numpy.ndarray

analysing a numpy array

In [ ]:
c = np.random.randint(1,10,(5,5))
print(c)

[[5 4 9 2 6]
 [8 5 3 4 2]
 [4 2 3 4 4]
 [4 5 6 2 7]
 [3 1 5 4 6]]


In [ ]:
c.shape

(5, 5)

In [ ]:
print(c.ndim)

2


In [ ]:
b = np.random.randint(1,10,(4,4,4))
print(b)

[[[1 4 4 2]
  [9 8 6 2]
  [7 4 1 2]
  [4 2 7 1]]

 [[6 4 1 8]
  [4 1 7 8]
  [6 7 2 1]
  [6 1 2 1]]

 [[7 8 3 5]
  [4 2 1 2]
  [1 1 2 9]
  [6 1 6 6]]

 [[7 3 9 4]
  [3 8 9 1]
  [5 2 3 1]
  [9 4 9 2]]]


In [ ]:
b.shape

(4, 4, 4)

In [ ]:
b.ndim

3

In [ ]:
b.size
c.size

25

In [ ]:
print(b.size)
print(c.size)

64
25


In [ ]:
# checking datatypes of the values
print(b.dtype)

int64


**MAth**

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
list1 = np.array([1,2,3,4,5])
list2 = np.array([6,7,8,9,10])

print(list1+list2)

[ 7  9 11 13 15]


In [ ]:
np.add(list1,list2)

array([ 7,  9, 11, 13, 15])

In [ ]:
np.subtract(list1,list2)

array([-5, -5, -5, -5, -5])

In [ ]:
np.multiply(list1,list2)

array([ 6, 14, 24, 36, 50])

In [ ]:
np.divide(list1,list2)

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
np.divide(list2,list1)

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [ ]:
np.sqrt(list1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [ ]:
np.exp(list2)

array([  403.42879349,  1096.63315843,  2980.95798704,  8103.08392758,
       22026.46579481])

In [ ]:
np.abs(list1)

array([1, 2, 3, 4, 5])

In [ ]:
np.clongfloat(7653478.78457)

(7653478.7845700001344+0j)

Array Manipulation

In [ ]:
b = np.random.randint(1,10,(2,3))
print(b)

[[4 7 2]
 [4 1 1]]


In [ ]:
print(np.transpose(b))
np.transpose(b).shape

[[4 4]
 [7 1]
 [2 1]]


(3, 2)

In [ ]:
np.size

<function size at 0x7a706ae53930>

In [ ]:
np.size(b)

9

In [ ]:
np.ndim(b)

2

In [ ]:
print(b.dtype)

int64


In [ ]:
g = b.reshape(3,2)
print(g)

[[4 7]
 [2 4]
 [1 1]]


In [ ]:
h = b.flatten()
print(h)

[4 7 2 4 1 1]


In [ ]:
j = b.ravel()
print(j)

[4 7 2 4 1 1]


In [ ]:
k = np.append(b,g)
print(k)

[4 7 2 4 1 1 4 7 2 4 1 1]


In [ ]:
q = np.delete(b,1)
print(q)

[4 2 4 1 1]


In [ ]:
s = np.random.randint(4,10,(3,4))
print(s)

[[5 4 9 9]
 [6 7 9 4]
 [5 5 5 6]]


In [ ]:
er = s.T
print(er)

[[5 6 5]
 [4 7 5]
 [9 9 5]
 [9 4 6]]


In [ ]:
s.T

array([[5, 6, 5],
       [4, 7, 5],
       [9, 9, 5],
       [9, 4, 6]])